import React from "react";
import Layout from "@/components/Layout";
import Head from "next/head";
import Link from "next/link";

function career() {
  return (
    <Layout>
      <div className="flex flex-col items-center justify-center min-h-screen px-5  mb-10 px-6 ">
        <Head>
          <title>김희민 포트폴리오</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <section className="text-gray-600 body-font">
          <div className="container flex flex-wrap px-5 py-24 mx-auto items-center">
            <div className="md:w-1/2 md:pr-12 md:py-8 md:border-r md:border-b-0 mb-10 md:mb-0 pb-10 border-b border-gray-200">
              <h1 className="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">
                (주식회사) 아워튜브
              </h1>
              <p className="leading-relaxed text-base">
                2022년 10월 12일 ~ 2023년 1월 11일 - 인턴
              </p>
              <Link
                href="ourtubeDetail"
                // target="_blank"
                className="text-indigo-500 inline-flex items-center mt-4"
              >
                More
                <svg
                  fill="none"
                  stroke="currentColor"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  className="w-4 h-4 ml-2"
                  viewBox="0 0 24 24"
                >
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </Link>
            </div>
            <div className="flex flex-col md:w-1/2 md:pl-12">
              <h2 className="title-font font-semibold text-gray-800 tracking-wider text-sm mb-3">
                사용,경험 기술
              </h2>
              <nav className="flex flex-wrap list-none -mb-1">
                <li className="lg:w-1/3 mb-1 w-1/2">
                  <a className="text-gray-600 hover:text-gray-800">React</a>
                </li>
                <li className="lg:w-1/3 mb-1 w-1/2">
                  <a className="text-gray-600 hover:text-gray-800">Axios</a>
                </li>
                <li className="lg:w-1/3 mb-1 w-1/2">
                  <a className="text-gray-600 hover:text-gray-800">
                    React query
                  </a>
                </li>
                <li className="lg:w-1/3 mb-1 w-1/2">
                  <a className="text-gray-600 hover:text-gray-800">Full page</a>
                </li>
                <li className="lg:w-1/3 mb-1 w-1/2">
                  <a className="text-gray-600 hover:text-gray-800">
                    Query string
                  </a>
                </li>
                <li className="lg:w-1/3 mb-1 w-1/2">
                  <a className="text-gray-600 hover:text-gray-800">
                    Youtube api
                  </a>
                </li>
                <li className="lg:w-1/3 mb-1 w-1/2">
                  <a className="text-gray-600 hover:text-gray-800">Kakao api</a>
                </li>
                <li className="lg:w-1/3 mb-1 w-1/2">
                  <a className="text-gray-600 hover:text-gray-800">
                    Infinite Scrolling
                  </a>
                </li>
                <li className="lg:w-1/3 mb-1 w-1/2">
                  <a className="text-gray-600 hover:text-gray-800">etc...</a>
                </li>
              </nav>
            </div>
          </div>
        </section>
      </div>
    </Layout>
  );
}

export default career;
